server:
  port: 8080

spring:
  application:
    name: gateway-service


  cloud:
    gateway:
      routes:
        - id: car-service
          uri: lb://CARS-SERVICE
          predicates:
            - Path=/car/**
          filters:
            - GateFilter


        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client/**
          filters:
            - GateFilter

        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
            - Path=/admin/**
          filters:
            GateFilter




eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true

