server:
  port: 8080

spring:
  application:
    name: gateway-service

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    name: unTalNikko
    password: pass3456

  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true


      routes:
        - id: client-service
          uri: http://localhost:8082
          predicates:
            - Path=/client/**

        - id: another-route
          uri:  http://localhost:8081
          predicates:
            - Path=/car/**