server:
  port: 8080

spring:
  application:
    name: gateway-service



  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true


      routes:
        - id: client-service
          uri: http://localhost:8082
          predicates:
            - Path=/client/**

        - id: car-service
          uri: http://localhost:8081
          predicates:
            - Path=/car/**

        - id: security-service
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**
            - Path=/admin/**