server:
  port: 9898

spring:
  application:
    name: security-service

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    username: unTalNikko
    password: pass3456
    driver-class-name: com.mysql.cj.jdbc.Driver