server:
  port: 9898

spring:
  name: security-service

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    name: unTalNikko
    password: pass3456